version: "3.1"

services:
  auth_service:
    container_name: auth_service
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - 7060:7060
    restart: always
